### PR TITLE
Task-51753 : ASC Sort of connections count column NOK in user analytics table

### PR DESCRIPTION
**Pull request by rdenarie**
Before this fix, the aggregation on dayOfYear was done in exo context instead of doing this in the ES request. This behaviour was added by this commit : 31753ae
As the aggregation shoud be counted on ES side, in the request, this commit rollback the problematic commit, and fix the initial aggregation by modifiing
doc['timestamp'].date to doc['timestamp'].value which is the correct way to use it with painless ES scripts

### CODE REVIEW

**Comment by rdenarie** [comment]
@boubaker can you check this PR ? We speak about on friday, but I had to modify something you initially did.
Please ping me if necessary

**Review by boubaker — COMMENTED** [review]
ok, so as far as the introduced bug was reverted it's ok for me. As discussed, the computing has to be done in ES side instead of JVM, and it worked fine before in ES 5.6. The modified computation from `date` to `value` seems not to be the good alternative, since in ES 7.x it should always be `doc['field_name'].date.dayOfYear`, see https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-scripting-expression.html
Let's take more time to get a better solution.

**Comment by rdenarie** [comment]
@boubaker as explained here : https://www.elastic.co/guide/en/elasticsearch//reference/current/breaking-changes-7.0.html#_getdate_and_getdates_removed
it seems that 
doc["timestamp"].date was removed in ES7, and we should use doc["timestamp"].value

**Comment by boubaker** [comment]
> @boubaker as explained here : https://www.elastic.co/guide/en/elasticsearch//reference/current/breaking-changes-7.0.html#_getdate_and_getdates_removed it seems that doc["timestamp"].date was removed in ES7, and we should use doc["timestamp"].value

They don't update their doc apparently everywhere :-)
So this is a new behavior in ES 7.x comparing to ES 5.x. Good catch !

**Review by boubaker — APPROVED** [review]

**Pull request merged**
